services:
  backend:
    build:
      context: ./server-springboot/threadverse
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=${MONGO_URI}
      - MONGO_DB=${MONGO_DB}
      - JWT_SECRET=${JWT_SECRET}

  frontend:
    build:
      context: ./client-react
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}
